# Generated by Django 6.0.1 on 2026-01-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_img', models.ImageField(upload_to='media')),
                ('event_name', models.CharField(max_length=30)),
                ('event_type', models.CharField(max_length=30)),
                ('event_price', models.BigIntegerField()),
                ('event_description', models.TextField()),
                ('package1', models.CharField(max_length=30)),
                ('package2', models.CharField(max_length=30)),
                ('package3', models.CharField(max_length=30)),
                ('package4', models.CharField(max_length=30)),
                ('mob_number', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=30)),
            ],
        ),
    ]
