# Generated by Django 6.0.1 on 2026-01-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(max_length=10)),
                ('event_company_name', models.CharField(max_length=30)),
                ('event_type', models.CharField(max_length=30)),
                ('event_price', models.BigIntegerField()),
                ('event_booking_date', models.CharField(max_length=10)),
                ('event_location', models.CharField(max_length=10)),
            ],
        ),
    ]
