# Generated by Django 6.0.1 on 2026-04-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_company',
            name='event_mobile_number',
            field=models.CharField(default='9287672041', max_length=10),
            preserve_default=False,
        ),
    ]
