# Generated by Django 6.0.1 on 2026-04-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_company_event_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_booking',
            name='event_mobile_number',
            field=models.CharField(default='1', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event_booking',
            name='event_location',
            field=models.CharField(max_length=30),
        ),
    ]
