# Generated by Django 6.0.1 on 2026-05-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_booking_event_mobile_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2002-05-30'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event_company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2002-05-30'),
            preserve_default=False,
        ),
    ]
